### ISSUE TITLE
no host isolation in the  EVPN/VXLAN bridging example

### ISSUE THREAD

**Issue by maloute** [ipspace/netlab-examples#10]
Hello,

I am following the 'EVPN/VXLAN bridging' example and it seems that this topology does not work as intended. In the topology.yml, 
It's clearly written that h1 should not ping h3, but in my example, this works, every hosts can ping each other.
As i did not install ceos, i've tried with s1&s2: cumulus vx image, and s1&s2: frr image, all within containerlab.

Do you have the same result ? or is there something wrong with my topology ? 

I can provide you the generated config file if needed.

Thank you,
Regards

**Comment by ipspace** [comment]
You're probably using the broken _netlab_ version where the host management IP addresses are in the Linux container /etc/hosts file https://github.com/ipspace/netlab/issues/536 -- I was steaming mad when I found out that particular side effect of a previous PR.

Please upgrade netlab to 1.3.3 with `pip3 install --upgrade networklab` and let me know if it works.

**Comment by maloute** [comment]
Thank you, that was the problem !
Awesome tool by the way, this really helps understanding and learning new protocols :)

**Comment by ipspace** [comment]
> Awesome tool by the way, this really helps understanding and learning new protocols :)

Thanks a million. Made my day ;)
