### ISSUE TITLE
https://github.com/ipspace/netlab-examples/tree/master/BGP/RR-sessions

### ISSUE THREAD

**Issue by helpdeskdan** [ipspace/netlab-examples#21]
<pre>
$ cat topology.yml 
#
# Using FRR on containerlab to make it fast
#
defaults.device: frr
provider: clab
#
module: [ isis, bgp ]

bgp.as_list:
  65000:
    members: [ rr1, rr2, pe1, pe2 ]
    rr: [ rr1, rr2 ]
  65001:
    members: [ x1 ]

groups:
  as65000:
    node_data:
      bgp.advertise_loopback: false

nodes: [ rr1, rr2, pe1, pe2, x1 ]

links: [ rr1-pe1, rr1-pe2, rr2-pe1, rr2-pe2, rr1-x1 ]
(netlab) ╭─dans@TheReplacement ~/rr-sessions 
╰─$ netlab up

┌──────────────────────────────────────────────────────────────────────────────────┐
│ CREATING configuration files                                                     │
└──────────────────────────────────────────────────────────────────────────────────┘
[ERRORS]  Errors found in topology.yml
[MISSING] bgp: Mandatory attribute topology.groups.as65000.node_data.bgp.as is missing
[FATAL]   Cannot proceed beyond this point due to errors, exiting
</pre>

_bgp.as: 65000_ missing under groups?

**Comment by ipspace** [comment]
I broke **bgp.as_list** functionality somewhere down the line (as in "obviously I forgot to create a unit test that would catch this one"). Will figure out what went wrong and fix either netlab code or this example.

Thank you!

**Comment by ipspace** [comment]
FWIW: it turns out **node_data** checking was too aggressive (more details in ipspace/netlab#1040). As it's an old feature, I made it deprecated and fixed the examples.

Thanks again for reporting this!
