### ISSUE TITLE
EVPN BGP Everywhere Lab for EOS Missing "maximum-paths 2" command Under BGP Config

### ISSUE THREAD

**Issue by andywhitaker** [ipspace/netlab-examples#24]
EBGP Everywhere lab appears to be missing `maximum-paths 2 ecmp 2` (or just `maximum-paths 2`) in the EOS BGP configs, so ECMP routes would not get installed.

**Comment by ipspace** [comment]
Thank you! We don't have that nerd knob in netlab just yet, so I will create custom configuration templates to set it up.
